import type { ComponentType } from "react";
import {
  BadgeCheck,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  ChartLine,
  CircleHelp,
  FileText,
  Flag,
  FlaskConical,
  Globe,
  Handshake,
  House,
  LayoutGrid,
  LifeBuoy,
  Newspaper,
  Package,
  Rocket,
  ScanSearch,
  ShieldCheck,
  Sparkles,
  WandSparkles,
  Workflow,
} from "lucide-react";
import {
  FacebookIcon,
  GitHubIcon,
  InstagramIcon,
  LinkedInIcon,
  TikTokIcon,
  WebsiteIcon,
  XIcon,
  YouTubeIcon,
} from "@/components/icons/social-icons";

type IconProps = { className?: string };

export const NAVIGATION_ICON_MAP: Record<string, ComponentType<IconProps>> = {
  home: House,
  grid: LayoutGrid,
  product: Package,
  service: BriefcaseBusiness,
  blog: Newspaper,
  docs: BookOpen,
  page: FileText,
  company: Building2,
  contact: Handshake,
  pricing: BadgeCheck,
  growth: ChartLine,
  rocket: Rocket,
  ai: Sparkles,
  magic: WandSparkles,
  workflow: Workflow,
  security: ShieldCheck,
  search: ScanSearch,
  support: LifeBuoy,
  help: CircleHelp,
  global: Globe,
  labs: FlaskConical,
  program: Flag,
  // backward compatibility with older nav values
  facebook: FacebookIcon,
  instagram: InstagramIcon,
  x: XIcon,
  youtube: YouTubeIcon,
  linkedin: LinkedInIcon,
  tiktok: TikTokIcon,
  github: GitHubIcon,
  website: WebsiteIcon,
};
